// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaComponentesObdulio.Data;

#nullable disable

namespace PruebaComponentesObdulio.Migrations
{
    [DbContext(typeof(TiendaOrdenadoresContext))]
    [Migration("20230910103824_MigracionparaAPisinpedidos")]
    partial class MigracionparaAPisinpedidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaComponentesObdulio.Models.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calor")
                        .HasColumnType("int");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<double>("Coste")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Megas")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PedidoComponentesId")
                        .HasColumnType("int");

                    b.Property<int>("TipoComponente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoComponentesId");

                    b.ToTable("Componentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calor = 10,
                            Cores = 9,
                            Coste = 134.0,
                            Descripcion = "Procesador Intel i7",
                            Megas = 0L,
                            NumeroSerie = "789_XCS",
                            TipoComponente = 0
                        },
                        new
                        {
                            Id = 2,
                            Calor = 12,
                            Cores = 10,
                            Coste = 138.0,
                            Descripcion = "Procesador Intel i7",
                            Megas = 0L,
                            NumeroSerie = "789_XCD",
                            TipoComponente = 0
                        },
                        new
                        {
                            Id = 3,
                            Calor = 22,
                            Cores = 11,
                            Coste = 138.0,
                            Descripcion = "Procesador Intel i7",
                            Megas = 0L,
                            NumeroSerie = "789_XCT",
                            TipoComponente = 0
                        },
                        new
                        {
                            Id = 4,
                            Calor = 10,
                            Cores = 0,
                            Coste = 100.0,
                            Descripcion = "Banco de memoria SDRAM",
                            Megas = 512L,
                            NumeroSerie = "879FH",
                            TipoComponente = 1
                        },
                        new
                        {
                            Id = 5,
                            Calor = 15,
                            Cores = 0,
                            Coste = 125.0,
                            Descripcion = "Banco de memoria SDRAM",
                            Megas = 1024L,
                            NumeroSerie = "879FH_L",
                            TipoComponente = 1
                        },
                        new
                        {
                            Id = 6,
                            Calor = 24,
                            Cores = 0,
                            Coste = 150.0,
                            Descripcion = "Banco de memoria SDRAM",
                            Megas = 2028L,
                            NumeroSerie = "879FH_T",
                            TipoComponente = 1
                        },
                        new
                        {
                            Id = 7,
                            Calor = 10,
                            Cores = 0,
                            Coste = 50.0,
                            Descripcion = "Disco Duro Scan Disk",
                            Megas = 500000L,
                            NumeroSerie = "789_XX",
                            TipoComponente = 2
                        },
                        new
                        {
                            Id = 8,
                            Calor = 29,
                            Cores = 0,
                            Coste = 90.0,
                            Descripcion = "Disco Duro Scan Disk",
                            Megas = 1000000L,
                            NumeroSerie = "789_XX_2",
                            TipoComponente = 2
                        },
                        new
                        {
                            Id = 9,
                            Calor = 39,
                            Cores = 0,
                            Coste = 128.0,
                            Descripcion = "Disco Duro Scan Disk",
                            Megas = 2000000L,
                            NumeroSerie = "789_XX_3",
                            TipoComponente = 2
                        },
                        new
                        {
                            Id = 10,
                            Calor = 30,
                            Cores = 10,
                            Coste = 78.0,
                            Descripcion = "Procesador Ryzen AMD",
                            Megas = 0L,
                            NumeroSerie = "797-X",
                            TipoComponente = 0
                        },
                        new
                        {
                            Id = 11,
                            Calor = 30,
                            Cores = 29,
                            Coste = 178.0,
                            Descripcion = "Procesador Ryzen AMD",
                            Megas = 0L,
                            NumeroSerie = "797-X-2",
                            TipoComponente = 0
                        },
                        new
                        {
                            Id = 12,
                            Calor = 60,
                            Cores = 34,
                            Coste = 278.0,
                            Descripcion = "Procesador Ryzen AMD",
                            Megas = 0L,
                            NumeroSerie = "797-X-3",
                            TipoComponente = 0
                        },
                        new
                        {
                            Id = 13,
                            Calor = 35,
                            Cores = 0,
                            Coste = 37.0,
                            Descripcion = "Disco Mecanico Patatin",
                            Megas = 250L,
                            NumeroSerie = "788-fg",
                            TipoComponente = 2
                        },
                        new
                        {
                            Id = 14,
                            Calor = 35,
                            Cores = 0,
                            Coste = 67.0,
                            Descripcion = "Disco Mecanico Patatin",
                            Megas = 250L,
                            NumeroSerie = "788-fg-2",
                            TipoComponente = 2
                        },
                        new
                        {
                            Id = 15,
                            Calor = 35,
                            Cores = 0,
                            Coste = 97.0,
                            Descripcion = "Disco Mecanico Patatin",
                            Megas = 250L,
                            NumeroSerie = "788-fg-3",
                            TipoComponente = 2
                        });
                });

            modelBuilder.Entity("PruebaComponentesObdulio.Models.Ordenador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PedidoOrdenadoresId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tipoOrdenador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoOrdenadoresId");

                    b.ToTable("Ordenadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Almacen de componentes",
                            PrecioTotal = 0m,
                            tipoOrdenador = 0
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Ordenador de Maria",
                            PrecioTotal = 284m,
                            tipoOrdenador = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Ordenador de Andres",
                            PrecioTotal = 556m,
                            tipoOrdenador = 2
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Ordenador de Tiburcio",
                            PrecioTotal = 455m,
                            tipoOrdenador = 3
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Ordenador de AndresCF",
                            PrecioTotal = 593m,
                            tipoOrdenador = 4
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Ordenador personalizado",
                            PrecioTotal = 0m,
                            tipoOrdenador = 5
                        });
                });

            modelBuilder.Entity("PruebaComponentesObdulio.Models.PedidoComponentes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PedidoComponentes");
                });

            modelBuilder.Entity("PruebaComponentesObdulio.Models.PedidoOrdenadores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PedidoOrdenadores");
                });

            modelBuilder.Entity("PruebaComponentesObdulio.Models.Componente", b =>
                {
                    b.HasOne("PruebaComponentesObdulio.Models.PedidoComponentes", null)
                        .WithMany("LPComponentes")
                        .HasForeignKey("PedidoComponentesId");
                });

            modelBuilder.Entity("PruebaComponentesObdulio.Models.Ordenador", b =>
                {
                    b.HasOne("PruebaComponentesObdulio.Models.PedidoOrdenadores", null)
                        .WithMany("LPOrdenadores")
                        .HasForeignKey("PedidoOrdenadoresId");
                });

            modelBuilder.Entity("PruebaComponentesObdulio.Models.PedidoComponentes", b =>
                {
                    b.Navigation("LPComponentes");
                });

            modelBuilder.Entity("PruebaComponentesObdulio.Models.PedidoOrdenadores", b =>
                {
                    b.Navigation("LPOrdenadores");
                });
#pragma warning restore 612, 618
        }
    }
}
